# Generated by Django 4.2.1 on 2023-06-11 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='general_settings',
            options={'ordering': ('name',), 'verbose_name': 'General Settings', 'verbose_name_plural': 'General Settings'},
        ),
        migrations.AlterField(
            model_name='general_settings',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created_date'),
        ),
        migrations.AlterField(
            model_name='general_settings',
            name='description',
            field=models.CharField(blank=True, default='', max_length=254, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='general_settings',
            name='name',
            field=models.CharField(blank=True, default='', max_length=254, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='general_settings',
            name='parameter',
            field=models.CharField(blank=True, default='', max_length=254, verbose_name='parameter'),
        ),
        migrations.AlterField(
            model_name='general_settings',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, verbose_name='update_date'),
        ),
    ]
