# Generated by Django 4.2.1 on 2023-06-15 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_experience_alter_skill_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='update_date')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created_date')),
                ('edu_name', models.CharField(blank=True, default='', max_length=254, verbose_name='Education Name')),
                ('edu_title', models.CharField(blank=True, default='', max_length=254, verbose_name='Education Title')),
                ('edu_location', models.CharField(blank=True, default='', max_length=254, verbose_name='Education Location')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, default=None, null=True, verbose_name='End Date')),
            ],
            options={
                'verbose_name': 'Education',
                'verbose_name_plural': 'Education',
                'ordering': ('start_date',),
            },
        ),
    ]
