version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - resume/docker.env
    volumes:
      - .:/srv/app
    ports:
      - "0.0.0.0:8000:8000"
    command: python3 manage.py runserver 0.0.0.0:8000
  postgres:
    image: postgres:latest
    env_file:
      - resume/docker.env
    ports:
      - "5432:5432"
    volumes:
      - "postgres-data:/var/lib/postgresql/data"
    command: -p 5432
    
volumes:
  static-data:
